spring:
  application:
    name: 'user-service-api' #nome no meu componente
  data:
    mongodb:
      uri: 'mongodb+srv://help-desk-user:davieisaac@clusterhelpdesk.lxyvszq.mongodb.net/dbhelpdesk?retryWrites=true&w=majority&appName=ClusterHelpDesk'
      auto-index-creation: true #cria index dos users
      #porta padrão do mongo 27017
