spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      uri: 'mongodb+srv://help-desk-user:davieisaac@clusterhelpdesk.lxyvszq.mongodb.net/dbhelpdesk?retryWrites=true&w=majority&appName=ClusterHelpDesk'
      auto-index-creation: true

springdoc:
  openapi:
  title: 'User-Service-API'
  description: 'Java Expert com o professor Valdir Cesar'
  version: '1.0.0'

server:
  port: ${SERVER_PORT:8080}